#!/usr/bin/env python3
"""Export the dependencies table to portable SQL INSERT statements.

Usage (Windows):
    python scripts/export_dependencies.py > dependencies_export.sql

Then copy dependencies_export.sql to the Ubuntu server and run:
    python scripts/export_dependencies.py --import dependencies_export.sql
Or use sqlite3 CLI directly:
    sqlite3 rag_service.db < dependencies_export.sql
"""
import argparse
import sqlite3
import sys
from pathlib import Path


def _load_db_path() -> str:
    env_file = Path(__file__).parent.parent / ".env"
    db_path = "./rag_service.db"
    if env_file.exists():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("DATABASE_PATH="):
                db_path = line.split("=", 1)[1].strip()
                break
    return str((Path(__file__).parent.parent / db_path).resolve())


DB_PATH = _load_db_path()


def export_sql(conn: sqlite3.Connection) -> str:
    """Export dependencies table as idempotent SQL INSERT OR IGNORE statements."""
    conn.row_factory = sqlite3.Row
    rows = conn.execute(
        "SELECT id, dataset_id, source, target_doc_id, created_at, updated_at "
        "FROM dependencies ORDER BY created_at"
    ).fetchall()

    lines = [
        "-- dependencies table export",
        "-- Generated by scripts/export_dependencies.py",
        f"-- Total rows: {len(rows)}",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for row in rows:
        values = ", ".join([
            f"'{row['id']}'",
            f"'{row['dataset_id']}'",
            f"'{row['source']}'",
            f"'{row['target_doc_id']}'",
            f"'{row['created_at']}'",
            f"'{row['updated_at']}'",
        ])
        lines.append(
            f"INSERT OR IGNORE INTO dependencies "
            f"(id, dataset_id, source, target_doc_id, created_at, updated_at) "
            f"VALUES ({values});"
        )

    lines += ["", "COMMIT;", ""]
    return "\n".join(lines)


def import_sql(db_path: str, sql_file: str):
    """Import SQL file into target database."""
    sql = Path(sql_file).read_text(encoding="utf-8")
    conn = sqlite3.connect(db_path)
    try:
        conn.executescript(sql)
        conn.commit()
        # Count imported rows
        count = conn.execute("SELECT COUNT(*) FROM dependencies").fetchone()[0]
        print(f"Done. dependencies table now has {count} rows.")
    finally:
        conn.close()


def main():
    parser = argparse.ArgumentParser(description="Export/import dependencies table")
    parser.add_argument(
        "--import", dest="import_file", metavar="FILE",
        help="Import SQL file into the database instead of exporting"
    )
    parser.add_argument(
        "--db", default=DB_PATH,
        help=f"Database path (default: {DB_PATH})"
    )
    args = parser.parse_args()

    if args.import_file:
        print(f"Importing {args.import_file} → {args.db}", file=sys.stderr)
        import_sql(args.db, args.import_file)
    else:
        conn = sqlite3.connect(args.db)
        conn.row_factory = sqlite3.Row
        try:
            print(export_sql(conn))
        finally:
            conn.close()


if __name__ == "__main__":
    main()
